//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.04 at 03:07:50 PM WIB 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/perpustakaan/soap", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.perpustakaan.soap;
